### ISSUE TITLE
Improve mobile view

### ISSUE THREAD

**Issue by smtbhd32** [Shvm17/std-percent-calc#1]
### **### Delete outer margin in mobile view and merge both sections**

![image](https://user-images.githubusercontent.com/95293951/152248740-14caeea3-4c87-4ea9-802d-e813d13f8a6a.png)

**Comment by smtbhd32** [comment]
### Use the highlighted space, no need for a separate container in mobile view...


![image](https://user-images.githubusercontent.com/95293951/152249521-90bda501-e5ef-460c-8a8d-cbd14c51934d.png)

**Comment by Shvm17** [comment]
There is an issue, while we type input the size of the container get
decreases and causes some disturbance that effects button and marred the
whole look .
The purpose of giving some extra space is to overcome this problem .
And i have also did hit and trials to get relevant look.

**Comment by smtbhd32** [comment]
There is issue and we are here to solve this issue.
Open the issue again...
Try to solve it...
Mention the pull requests...
Solved.
Close the issue...
