### ISSUE TITLE
Input tag Issue

### ISSUE THREAD

**Issue by smtbhd32** [Shvm17/std-percent-calc#2]
Make sure that the highlighted part should only be visible on hover or you can entirely remove that.
It's deteriorating the look.

![image](https://user-images.githubusercontent.com/95293951/152249100-4d55a257-7c5e-43b2-8813-e7308f6166d5.png)

**Comment by Shvm17** [comment]
Ok i got your point, but in my mobile view the highlighted part is only
visible on hover .
If problem persists to me , then I will counter this issue.
